import type { RoleDef, RoleId } from '../types.js'
import { PALETTE } from './palette.js'

/**
 * Six roles. Duplicates are allowed but the second player on a role takes a
 * flat "unclear ownership" penalty, which is both a balance lever and the truest
 * thing in this file.
 *
 * Travel & Claims is deliberately the worst class on the sheet for waves 1-5 and
 * the reason the lobby survives waves 9+. The joke only lands if it is true.
 */
export const ROLES: Record<RoleId, RoleDef> = {
  hrbp: {
    id: 'hrbp',
    name: 'HRBP',
    title: 'HR Business Partner',
    flavour: 'Strategic. Allegedly. Spends 70% of the wave in a meeting about the wave.',
    specialistPower: 2.2,
    specialistTargets: ['er_case', 'support_squirrel'],
    seesStealth: true,
    ignoredByRequests: false,
    refusesBuffs: false,
    losesAbilityEachWave: true,
    contactDamage: 3,
    colour: PALETTE.deckBlue,
    sprite: 'pc_hrbp',
    abilities: [
      {
        id: 'alignment',
        name: 'Stakeholder Alignment',
        flavour: 'You got them in a room. Briefly. Towers nearby hit 25% harder.',
        key: 'Q',
        cooldownSeconds: 18,
        kind: 'buff_towers',
        radius: 6,
        durationSeconds: 8,
        amount: 0.25,
      },
      {
        id: 'difficult_conversation',
        name: 'Difficult Conversation',
        flavour: 'The one nobody else will have. Heavy single-target damage.',
        key: 'W',
        cooldownSeconds: 17,
        kind: 'single_target',
        damage: 60,
        radius: 4,
      },
      {
        id: 'reveal_er',
        name: 'Skip-Level',
        flavour: 'You asked someone how they were actually doing. Reveals hidden cases.',
        key: 'E',
        cooldownSeconds: 24,
        kind: 'reveal',
        radius: 9,
        durationSeconds: 10,
      },
      {
        id: 'buy_in',
        name: 'Executive Buy-In',
        flavour: 'They said yes in the room. Get it in writing before they leave. +40 Social Capital.',
        key: 'R',
        cooldownSeconds: 180,
        kind: 'grant_social',
        amount: 40,
      },
    ],
  },

  payroll: {
    id: 'payroll',
    name: 'Payroll',
    title: 'Payroll Specialist',
    flavour: 'The only person in this building whose deadline is a law. Immovable. Correct. Tired.',
    specialistPower: 2.0,
    specialistTargets: ['payroll_discrepancy'],
    seesStealth: false,
    ignoredByRequests: false,
    refusesBuffs: false,
    losesAbilityEachWave: false,
    contactDamage: 4,
    colour: PALETTE.budget,
    sprite: 'pc_payroll',
    abilities: [
      {
        id: 'off_cycle',
        name: 'Off-Cycle Run',
        flavour: 'Deletes one Payroll Discrepancy outright. Finance will notice. Finance always notices.',
        key: 'Q',
        cooldownSeconds: 20,
        budgetCost: 40,
        kind: 'purge_tag',
        amount: 1,
      },
      {
        id: 'reconciliation',
        name: 'Reconciliation',
        flavour: 'Everything in the Payroll lane slows to your pace. Your pace is thorough.',
        key: 'W',
        cooldownSeconds: 26,
        kind: 'slow_lane',
        durationSeconds: 9,
        amount: 0.45,
      },
      {
        id: 'variance',
        name: 'Variance Report',
        flavour: 'Damage in a line. Every number on it is correct and somebody will still query it.',
        key: 'E',
        cooldownSeconds: 18,
        kind: 'line_damage',
        damage: 48,
        radius: 8,
      },
      {
        id: 'gross_to_net',
        name: 'Gross-To-Net',
        flavour: 'Clears every Payroll request on the board. Costs a frightening amount of Budget.',
        key: 'R',
        cooldownSeconds: 150,
        budgetCost: 120,
        kind: 'purge_tag',
        amount: 99,
      },
    ],
  },

  talent: {
    id: 'talent',
    name: 'Talent',
    title: 'Talent Acquisition',
    flavour: 'Solves the headcount problem by creating the onboarding problem. Beloved. Doomed.',
    specialistPower: 1.4,
    specialistTargets: ['onboarding_packet'],
    seesStealth: false,
    ignoredByRequests: false,
    refusesBuffs: false,
    losesAbilityEachWave: false,
    contactDamage: 3,
    colour: PALETTE.lanyardTeal,
    sprite: 'pc_talent',
    abilities: [
      {
        id: 'pipeline',
        name: 'Pipeline',
        flavour: 'Summons an Intern. The Intern fights for 20 seconds and then, correctly, leaves.',
        key: 'Q',
        cooldownSeconds: 22,
        kind: 'summon_intern',
        durationSeconds: 20,
      },
      {
        id: 'ghosting',
        name: 'Ghosting',
        flavour: 'Despawns one request. It will be back next wave, and it will remember.',
        key: 'W',
        cooldownSeconds: 16,
        kind: 'despawn',
        radius: 5,
      },
      {
        id: 'referral',
        name: 'Referral Bonus',
        flavour: 'Cone damage. Everyone suddenly knows someone perfect for the role.',
        key: 'E',
        cooldownSeconds: 16,
        kind: 'cone',
        damage: 40,
        radius: 6,
      },
      {
        id: 'sign_the_req',
        name: 'Sign The Req',
        flavour: '+2 permanent tower slots. Also six Onboarding Packets. Use it at the wrong moment and you end the run.',
        key: 'R',
        cooldownSeconds: 120,
        kind: 'summon_intern',
        amount: 2,
      },
    ],
  },

  rewards: {
    id: 'rewards',
    name: 'Rewards',
    title: 'Total Rewards',
    flavour: 'Deals more damage the longer they stand perfectly still. Spreadsheets require stillness.',
    specialistPower: 1.3,
    specialistTargets: ['benefits_enrollment'],
    seesStealth: false,
    ignoredByRequests: false,
    refusesBuffs: false,
    losesAbilityEachWave: false,
    contactDamage: 2,
    colour: PALETTE.social,
    sprite: 'pc_rewards',
    abilities: [
      {
        id: 'market_adjustment',
        name: 'Market Adjustment',
        flavour: 'Cone damage, benchmarked to the 50th percentile of the relevant comparator group.',
        key: 'Q',
        cooldownSeconds: 15,
        kind: 'cone',
        damage: 44,
        radius: 6,
      },
      {
        id: 'accrual',
        name: 'Bonus Accrual',
        flavour: 'Stores damage instead of dealing it. Pays out on your next ability. Vesting applies.',
        key: 'W',
        cooldownSeconds: 20,
        kind: 'store_damage',
        durationSeconds: 12,
      },
      {
        id: 'banding',
        name: 'Salary Banding',
        flavour: 'Slows everything in a radius into a defensible range.',
        key: 'E',
        cooldownSeconds: 18,
        kind: 'slow_lane',
        radius: 6,
        durationSeconds: 7,
        amount: 0.4,
      },
      {
        id: 'comp_cycle',
        name: 'RUN THE COMP CYCLE',
        flavour: '60-second channel. Board-wide annihilation. Interrupted if you move. You will be interrupted.',
        key: 'R',
        cooldownSeconds: 200,
        channelSeconds: 60,
        kind: 'channel_nuke',
        damage: 900,
      },
    ],
  },

  hris: {
    id: 'hris',
    name: 'HRIS',
    title: 'People Systems Analyst',
    flavour: 'Has admin rights and the quiet confidence of someone who has restored from backup before.',
    specialistPower: 1.2,
    specialistTargets: [],
    seesStealth: false,
    ignoredByRequests: false,
    refusesBuffs: false,
    losesAbilityEachWave: false,
    contactDamage: 2,
    colour: PALETTE.screenGlow,
    sprite: 'pc_hris',
    abilities: [
      {
        id: 'hotfix',
        name: 'Hotfix',
        flavour: 'Instantly repairs and reactivates the nearest offline tower. In production. On a Friday.',
        key: 'Q',
        cooldownSeconds: 15,
        kind: 'repair_tower',
        radius: 8,
      },
      {
        id: 'data_load',
        name: 'Data Load',
        flavour: 'Reveals every hidden case in a wide radius. You found them in a report, like always.',
        key: 'W',
        cooldownSeconds: 22,
        kind: 'reveal',
        radius: 12,
        durationSeconds: 8,
      },
      {
        id: 'field_audit',
        name: 'Field Audit',
        flavour: 'Single target. You found the actual root cause in nine seconds and told nobody.',
        key: 'E',
        cooldownSeconds: 16,
        kind: 'single_target',
        damage: 50,
        radius: 5,
      },
      {
        id: 'go_live',
        name: 'Go-Live',
        flavour: 'All towers fire at 3x for 15 seconds. Then an 8-second Maintenance Window kills every automation tower. Timing this is the entire class.',
        key: 'R',
        cooldownSeconds: 160,
        kind: 'overclock',
        durationSeconds: 15,
        amount: 3,
      },
    ],
  },

  travel: {
    id: 'travel',
    name: 'Travel & Claims',
    title: 'Mobility & Expenses',
    flavour: 'Nobody picks this. Nobody knows your name. You are the only counter to 30% of the game.',
    specialistPower: 2.5,
    specialistTargets: ['expense_claim', 'cat_sitter', 'the_mustang'],
    seesStealth: false,
    ignoredByRequests: true,
    refusesBuffs: true,
    losesAbilityEachWave: false,
    contactDamage: 2,
    colour: PALETTE.ashMauve,
    sprite: 'pc_travel',
    abilities: [
      {
        id: 'receipt_required',
        name: 'Receipt Required',
        flavour: 'Stops an Expense Claim from splitting. Four words. Load-bearing.',
        key: 'Q',
        cooldownSeconds: 10,
        kind: 'stop_split',
        radius: 6,
      },
      {
        id: 'mileage',
        name: 'Mileage',
        flavour: 'Chip damage in a line, calculated per kilometre at the approved rate.',
        key: 'W',
        cooldownSeconds: 13,
        kind: 'line_damage',
        damage: 36,
        radius: 9,
      },
      {
        id: 'policy_cap',
        name: 'Policy Cap',
        flavour: 'Slows everything nearby to the daily limit. The daily limit has not moved since 2016.',
        key: 'E',
        cooldownSeconds: 17,
        kind: 'slow_lane',
        radius: 6,
        durationSeconds: 8,
        amount: 0.5,
      },
      {
        id: 'per_diem',
        name: 'PER DIEM',
        flavour: 'Flat, unblockable, resistance-ignoring damage to everything on the board. Scales with the number of Expense Claims alive. Your hour has come.',
        key: 'R',
        cooldownSeconds: 140,
        kind: 'per_diem',
        damage: 60,
      },
    ],
  },
}

export const ROLE_IDS = Object.keys(ROLES) as RoleId[]

export function getRole(id: RoleId): RoleDef {
  const def = ROLES[id]
  if (!def) throw new Error(`Unknown role: ${id}`)
  return def
}
