import type { RoleId, StakeholderDef } from '../types.js'

/**
 * The enemy mirror of the classes.
 *
 * Requests walk to the CHRO door and cost you Morale. Stakeholders do something
 * categorically different: they walk to your **towers** and interfere with them.
 * That forces a different verb out of the player — you cannot out-build a
 * Stakeholder, you have to physically go and deal with it, which is what makes
 * the hero layer matter rather than being decoration on a tower defence.
 *
 * They are the same animals you play as. That is the joke, and it is also the
 * lesson: the thing wrecking your process is somebody doing their job the way
 * they have always done it.
 */
export const STAKEHOLDERS: Record<RoleId, StakeholderDef> = {
  hippo: {
    id: 'hippo',
    name: 'The HiPPO',
    title: 'Highest Paid Person in the Room',
    flavour: 'Has arrived at your standup. Has thoughts about the board. The board is not the problem.',
    hp: 420,
    speed: 0.7,
    interference: 'override',
    radius: 6,
    interval: 2,
    moraleDamage: 10,
    complianceDamage: 0,
    xp: 140,
    socialCapital: 8,
    dropChance: 0.35,
    sprite: 'sh_hippo',
  },
  zebra: {
    id: 'zebra',
    name: 'The Confident One',
    title: 'Zero Evidence, Full Certainty',
    flavour: 'Has replaced your validated figure with one they remember from a webinar.',
    hp: 260,
    speed: 1.2,
    interference: 'downgrade',
    radius: 4,
    interval: 4,
    moraleDamage: 6,
    complianceDamage: 0,
    xp: 95,
    socialCapital: 5,
    dropChance: 0.22,
    sprite: 'sh_zebra',
  },
  wolf: {
    id: 'wolf',
    name: 'The Firefighter',
    title: 'Needs There To Be A Fire',
    flavour: 'Has declared this an incident. It was not an incident until it was declared one.',
    hp: 300,
    speed: 1.9,
    interference: 'generate',
    radius: 3,
    interval: 5,
    moraleDamage: 5,
    complianceDamage: 0,
    xp: 110,
    socialCapital: 5,
    dropChance: 0.25,
    sprite: 'sh_wolf',
  },
  rhino: {
    id: 'rhino',
    name: 'The Absent Approver',
    title: 'Really Here In Name Only',
    flavour: 'Sits on the approval. Sits on it physically. The tower cannot work around them.',
    hp: 560,
    speed: 0.5,
    interference: 'disable',
    radius: 2,
    interval: 3,
    moraleDamage: 8,
    complianceDamage: 0,
    xp: 160,
    socialCapital: 9,
    dropChance: 0.38,
    sprite: 'sh_rhino',
  },
  seagull: {
    id: 'seagull',
    name: 'The Visiting Executive',
    title: 'Amuses, Glides, Unloads Loudly & Leaves',
    flavour: 'Down from group for the day. Will reorganise your function and be gone by four.',
    hp: 220,
    speed: 2.6,
    interference: 'unload',
    radius: 8,
    interval: 1,
    moraleDamage: 26,
    complianceDamage: 0,
    xp: 130,
    socialCapital: 12,
    dropChance: 0.45,
    sprite: 'sh_seagull',
  },
  goose: {
    id: 'goose',
    name: 'The Estimator',
    title: 'Guessing Overly, Scheduling Badly',
    flavour: 'Has promised your capacity to someone else. Your towers now reach half as far.',
    hp: 250,
    speed: 1.3,
    interference: 'shrink',
    radius: 6,
    interval: 3,
    moraleDamage: 5,
    complianceDamage: 0,
    xp: 100,
    socialCapital: 5,
    dropChance: 0.22,
    sprite: 'sh_goose',
  },
  puffin: {
    id: 'puffin',
    name: 'The Feature Factory',
    title: 'Plans Unending Initiatives',
    flavour: 'Every visit adds three items to your queue and removes none.',
    hp: 290,
    speed: 1.0,
    interference: 'generate',
    radius: 3,
    interval: 4,
    moraleDamage: 4,
    complianceDamage: 0,
    xp: 105,
    socialCapital: 5,
    dropChance: 0.24,
    sprite: 'sh_puffin',
  },
  puma: {
    id: 'puma',
    name: 'The Gut Feel',
    title: 'Promotes Unusually Mendacious Assumptions',
    flavour: 'Has reallocated your budget to something they have a feeling about.',
    hp: 270,
    speed: 1.6,
    interference: 'drain_budget',
    radius: 5,
    interval: 3,
    moraleDamage: 5,
    complianceDamage: 0,
    xp: 105,
    socialCapital: 6,
    dropChance: 0.26,
    sprite: 'sh_puma',
  },
  cobra: {
    id: 'cobra',
    name: 'The Certain',
    title: 'Cognitive Bias, Fully Committed',
    flavour: 'Knows what the problem is. Has known since before arriving. Overrules your towers.',
    hp: 310,
    speed: 1.2,
    interference: 'override',
    radius: 5,
    interval: 3,
    moraleDamage: 7,
    complianceDamage: 4,
    xp: 115,
    socialCapital: 6,
    dropChance: 0.27,
    sprite: 'sh_cobra',
  },
  yak: {
    id: 'yak',
    name: 'The Metrics Owner',
    title: 'Yet Another KPI',
    flavour: 'Needs a weekly report on the thing you are currently doing instead of doing it.',
    hp: 280,
    speed: 1.1,
    interference: 'drain_social',
    radius: 6,
    interval: 3,
    moraleDamage: 4,
    complianceDamage: 0,
    xp: 100,
    socialCapital: 4,
    dropChance: 0.23,
    sprite: 'sh_yak',
  },
  donkey: {
    id: 'donkey',
    name: 'The Data Requester',
    title: 'Data Only, No Why',
    flavour: 'Wants the extract. Will not say what for. Your towers narrow their focus to help.',
    hp: 240,
    speed: 1.4,
    interference: 'shrink',
    radius: 5,
    interval: 3,
    moraleDamage: 4,
    complianceDamage: 0,
    xp: 92,
    socialCapital: 4,
    dropChance: 0.2,
    sprite: 'sh_donkey',
  },
  mouse: {
    id: 'mouse',
    name: 'The Deferrer',
    title: 'Avoids Firm Decisions',
    flavour: 'Nothing gets closed while they are here. Everything nearby heals and lingers.',
    hp: 330,
    speed: 1.0,
    interference: 'rally',
    radius: 6,
    interval: 2,
    moraleDamage: 3,
    complianceDamage: 0,
    xp: 108,
    socialCapital: 5,
    dropChance: 0.24,
    sprite: 'sh_mouse',
  },
  viper: {
    id: 'viper',
    name: 'The Grudge',
    title: 'Vindictive Person Endangering Results',
    flavour: 'Is not here to interfere with a tower. Is here to remove it permanently.',
    hp: 380,
    speed: 1.5,
    interference: 'destroy',
    radius: 2,
    interval: 6,
    moraleDamage: 9,
    complianceDamage: 8,
    xp: 175,
    socialCapital: 11,
    dropChance: 0.42,
    sprite: 'sh_viper',
  },
  dodo: {
    id: 'dodo',
    name: 'The Old Guard',
    title: 'Dangerously Outdated Opinions',
    flavour: 'Has reverted your process to the version they were trained on.',
    hp: 350,
    speed: 0.8,
    interference: 'downgrade',
    radius: 4,
    interval: 4,
    moraleDamage: 7,
    complianceDamage: 0,
    xp: 125,
    socialCapital: 7,
    dropChance: 0.3,
    sprite: 'sh_dodo',
  },
}

export const STAKEHOLDER_IDS = Object.keys(STAKEHOLDERS) as RoleId[]

export function getStakeholder(id: RoleId): StakeholderDef {
  const def = STAKEHOLDERS[id]
  if (!def) throw new Error(`Unknown stakeholder: ${id}`)
  return def
}

/** What each one says on arrival. Verbatim energy. */
export const STAKEHOLDER_BARKS: Record<RoleId, string[]> = {
  hippo: ['just dropping in', 'quick steer', 'I have a view on this'],
  zebra: ['that number looks wrong', 'I read something different', 'are we sure about that'],
  wolf: ['I am declaring an incident', 'all hands', 'this is now P1'],
  rhino: ['still reviewing', 'it is in my queue', 'I will get to it'],
  seagull: ['while I am here', 'one observation', 'I will leave that with you'],
  goose: ['should be quick', 'I told them Friday', 'you have capacity, right'],
  puffin: ['small addition', 'while we are in there', 'can we also'],
  puma: ['I have moved the budget', 'trust me', 'this feels bigger'],
  cobra: ['I know what this is', 'seen it before', 'that is not the issue'],
  yak: ['can I get a weekly on this', 'is there a dashboard', 'what does good look like'],
  donkey: ['can you send the extract', 'all fields please', 'no particular reason'],
  mouse: ['let us not decide today', 'worth another look', 'who else should see this'],
  viper: ['I raised this in March', 'I have the email', 'interesting choice'],
  dodo: ['we never used to need this', 'the old form was fine', 'put it back'],
}
